export const USB_POLLING_INTERVAL = 200
export const USB_LONG_VALUE_WRITE_DELAY = 1000
export const CHECK_ICON = '✓'
export const KEY_ICON = '🔑'
export const BALLOT_BOX_ICON = '🗳️'
export const LOCKED_ICON = '🔒'
export const UNLOCKED_ICON = '🔓'
export const LOCKED_ICON_WITH_KEY = '🔐'
export const MAX_TRUSTEES = 5
export const MAX_ENCRYPTERS = 5
export const FONT_SIZES = [22, 30, 36, 48]
export const DEFAULT_FONT_SIZE = 1
export const LARGE_DISPLAY_FONT_SIZE = 3
export const TEXT_SIZE = 1
